;;; hyrule-theme.el --- an Emacs 24 theme based on Hyrule (tmTheme)
;;
;;; Author: Auto Converted to Emacs 24 by tmtheme-to-deftheme (tm2deftheme)
;;; Version: 1533971953
;;; Original author: 
;;; Url: https://github.com/emacsfodder/tmtheme-to-deftheme
;;; Package-Requires: ((emacs "24.0"))
;;
;;; Commentary:
;;  This theme was automatically generated by tmtheme-to-deftheme (tm2deftheme),
;;  from Hyrule (tmTheme) by 
;;
;;; Code:

(deftheme hyrule
  "hyrule-theme - Created by tmtheme-to-deftheme - 2018-08-11 09:19:13 +0200")

(custom-theme-set-variables
 'hyrule
)

(custom-theme-set-faces
 'hyrule
 ;; basic theming.

 '(default ((t (:foreground "#c0d5c1" :background "#2d2c2b" ))))
 '(region  ((t (:background "#569e16"))))
 '(cursor  ((t (:background "#f8f8f0"))))

 ;; Temporary defaults
 '(linum                               ((t (:foreground "#4a4e49"  :background "#3c3d3a" ))))
 '(fringe                              ((t (                       :background "#3c3d3a" ))))

 '(minibuffer-prompt                   ((t (:foreground "#1278A8"  :background nil       :weight bold                                  ))))
 '(escape-glyph                        ((t (:foreground "orange"   :background nil                                                     ))))
 '(highlight                           ((t (:foreground "orange"   :background nil                                                     ))))
 '(shadow                              ((t (:foreground "#777777"  :background nil                                                     ))))

 '(trailing-whitespace                 ((t (:foreground "#FFFFFF"  :background "#C74000"                                               ))))
 '(link                                ((t (:foreground "#00b7f0"  :background nil       :underline t                                  ))))
 '(link-visited                        ((t (:foreground "#4488cc"                        :underline t :inherit (link)                  ))))
 '(button                              ((t (:foreground "#FFFFFF"  :background "#444444" :underline t :inherit (link)                  ))))
 '(next-error                          ((t (                                             :inherit (region)                             ))))
 '(query-replace                       ((t (                                             :inherit (isearch)                            ))))
 '(header-line                         ((t (:foreground "#EEEEEE"  :background "#444444" :box nil :inherit (mode-line)                 ))))

 '(mode-line-highlight                 ((t (                                             :box nil                                      ))))
 '(mode-line-emphasis                  ((t (                                             :weight bold                                  ))))
 '(mode-line-buffer-id                 ((t (                                             :box nil :weight bold                         ))))

 '(mode-line-inactive                  ((t (:foreground "#8fb591"  :background "#3c3d3a" :box nil :weight light :inherit (mode-line)   ))))
 '(mode-line                           ((t (:foreground "#c0d5c1"  :background "#3c3d3a" :box nil ))))

 '(isearch                             ((t (:foreground "#99ccee"  :background "#444444"                                               ))))
 '(isearch-fail                        ((t (                       :background "#ffaaaa"                                               ))))
 '(lazy-highlight                      ((t (                       :background "#77bbdd"                                               ))))
 '(match                               ((t (                       :background "#3388cc"                                               ))))

 '(tooltip                             ((t (:foreground "black"    :background "LightYellow" :inherit (variable-pitch)                 ))))

 '(js3-function-param-face             ((t (:foreground "#BFC3A9"                                                                      ))))
 '(js3-external-variable-face          ((t (:foreground "#F0B090"  :bold t                                                             ))))

 '(secondary-selection                 ((t (                       :background "#342858"                                               ))))
 '(cua-rectangle                       ((t (:foreground "#E0E4CC"  :background "#342858" ))))

 ;; Magit hightlight
 '(magit-item-highlight                ((t (:foreground "white" :background "#1278A8" :inherit nil ))))

 ;; flyspell-mode
 '(flyspell-incorrect                  ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flyspell-duplicate                  ((t (:underline "#009945" :background nil :inherit nil ))))

 ;; flymake-mode
 '(flymake-errline                     ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flymake-warnline                    ((t (:underline "#009945" :background nil :inherit nil ))))

 ;;git-gutter
 '(git-gutter:added                    ((t (:foreground "#609f60" :bold t))))
 '(git-gutter:modified                 ((t (:foreground "#3388cc" :bold t))))
 '(git-gutter:deleted                  ((t (:foreground "#cc3333" :bold t))))

 '(diff-added                          ((t (:background "#305030"))))
 '(diff-removed                        ((t (:background "#903010"))))
 '(diff-file-header                    ((t (:background "#362145"))))
 '(diff-context                        ((t (:foreground "#E0E4CC"))))
 '(diff-changed                        ((t (:foreground "#3388cc"))))
 '(diff-hunk-header                    ((t (:background "#242130"))))


 '(font-lock-comment-face ((t (:foreground "#716d6a"  ))))
 '(font-lock-string-face ((t (:foreground "#ce830d"  ))))
 '(font-lock-builtin-face ((t (:foreground "#569e16"  ))))
 '(font-lock-variable-name-face ((t (  ))))
 '(font-lock-keyword-face ((t (:foreground "#90c93f"  ))))
 '(font-lock-type-face ((t (:foreground "#569e16"  :underline t))))
 '(font-lock-function-name-face ((t (:foreground "#90c93f"  ))))
 '(js3-function-param-face ((t (  :italic t))))
 '(js2-function-param ((t (  :italic t))))
 '(font-lock-warning-face ((t (:foreground "#f8f8f0" :background "#00a8c6" ))))
 '(diff-removed ((t (:foreground "#00A8C6"  ))))
 '(diff-added ((t (:foreground "#A6E22E"  ))))
 '(diff-changed ((t (:foreground "#E6DB74"  ))))
 '(markdown-header-face ((t (:foreground "#569e16"  ))))
 '(markdown-inline-code-face ((t (:foreground "#ce830d"  ))))
 '(markdown-bold-face ((t (:foreground "#90c93f"  ))))
 '(markdown-pre-face ((t (:foreground "#00a8c6"  ))))
 '(git-gutter:deleted ((t (:foreground "#e61f44"  ))))
 '(git-gutter:added ((t (:foreground "#a7da1e"  ))))
 '(git-gutter:modified ((t (:foreground "#f7b83d"  ))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#716d6a"  ))))

;; Rainbow delimiters
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#3d6f0f"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#437a11"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#498613"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#4f9114"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#559c16"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#5ba717"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#61b219"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#67bd1a"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#6dc81c"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#FF0000"))))
) ;; End face definitions

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'hyrule)

;; Local Variables:
;; eval: (when (fboundp 'rainbow-mode) (rainbow-mode +1))
;; End:

;;; hyrule-theme.el ends here
