;;; ayu-theme.el --- an Emacs 24 theme based on ayu (tmTheme)
;;
;;; Author: Auto Converted to Emacs 24 by tmtheme-to-deftheme (tm2deftheme)
;;; Version: 1533971274
;;; Original author: Ike Ku
;;; Url: https://github.com/emacsfodder/tmtheme-to-deftheme
;;; Package-Requires: ((emacs "24.0"))
;;
;;; Commentary:
;;  This theme was automatically generated by tmtheme-to-deftheme (tm2deftheme),
;;  from ayu (tmTheme) by Ike Ku
;;
;;; Code:

(deftheme ayu_dark
  "ayu_dark-theme - Created by tmtheme-to-deftheme - 2018-08-11 09:07:54 +0200")

(custom-theme-set-variables
 'ayu_dark
)

(custom-theme-set-faces
 'ayu_dark
 ;; basic theming.

 '(default ((t (:foreground "#BFBAB0" :background "#0F1419" ))))
 '(region  ((t (:background "#16242E"))))
 '(cursor  ((t (:background "#F29718"))))

 ;; Temporary defaults
 '(linum                               ((t (:foreground "#323537"  :background "#212528" ))))
 '(fringe                              ((t (                       :background "#212528" ))))

 '(minibuffer-prompt                   ((t (:foreground "#1278A8"  :background nil       :weight bold                                  ))))
 '(escape-glyph                        ((t (:foreground "orange"   :background nil                                                     ))))
 '(highlight                           ((t (:foreground "orange"   :background nil                                                     ))))
 '(shadow                              ((t (:foreground "#777777"  :background nil                                                     ))))

 '(trailing-whitespace                 ((t (:foreground "#FFFFFF"  :background "#C74000"                                               ))))
 '(link                                ((t (:foreground "#00b7f0"  :background nil       :underline t                                  ))))
 '(link-visited                        ((t (:foreground "#4488cc"                        :underline t :inherit (link)                  ))))
 '(button                              ((t (:foreground "#FFFFFF"  :background "#444444" :underline t :inherit (link)                  ))))
 '(next-error                          ((t (                                             :inherit (region)                             ))))
 '(query-replace                       ((t (                                             :inherit (isearch)                            ))))
 '(header-line                         ((t (:foreground "#EEEEEE"  :background "#444444" :box nil :inherit (mode-line)                 ))))

 '(mode-line-highlight                 ((t (                                             :box nil                                      ))))
 '(mode-line-emphasis                  ((t (                                             :weight bold                                  ))))
 '(mode-line-buffer-id                 ((t (                                             :box nil :weight bold                         ))))

 '(mode-line-inactive                  ((t (:foreground "#9e9787"  :background "#212528" :box nil :weight light :inherit (mode-line)   ))))
 '(mode-line                           ((t (:foreground "#bfbab0"  :background "#212528" :box nil ))))

 '(isearch                             ((t (:foreground "#99ccee"  :background "#444444"                                               ))))
 '(isearch-fail                        ((t (                       :background "#ffaaaa"                                               ))))
 '(lazy-highlight                      ((t (                       :background "#77bbdd"                                               ))))
 '(match                               ((t (                       :background "#3388cc"                                               ))))

 '(tooltip                             ((t (:foreground "black"    :background "LightYellow" :inherit (variable-pitch)                 ))))

 '(js3-function-param-face             ((t (:foreground "#BFC3A9"                                                                      ))))
 '(js3-external-variable-face          ((t (:foreground "#F0B090"  :bold t                                                             ))))

 '(secondary-selection                 ((t (                       :background "#342858"                                               ))))
 '(cua-rectangle                       ((t (:foreground "#E0E4CC"  :background "#342858" ))))

 ;; Magit hightlight
 '(magit-item-highlight                ((t (:foreground "white" :background "#1278A8" :inherit nil ))))

 ;; flyspell-mode
 '(flyspell-incorrect                  ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flyspell-duplicate                  ((t (:underline "#009945" :background nil :inherit nil ))))

 ;; flymake-mode
 '(flymake-errline                     ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flymake-warnline                    ((t (:underline "#009945" :background nil :inherit nil ))))

 ;;git-gutter
 '(git-gutter:added                    ((t (:foreground "#609f60" :bold t))))
 '(git-gutter:modified                 ((t (:foreground "#3388cc" :bold t))))
 '(git-gutter:deleted                  ((t (:foreground "#cc3333" :bold t))))

 '(diff-added                          ((t (:background "#305030"))))
 '(diff-removed                        ((t (:background "#903010"))))
 '(diff-file-header                    ((t (:background "#362145"))))
 '(diff-context                        ((t (:foreground "#E0E4CC"))))
 '(diff-changed                        ((t (:foreground "#3388cc"))))
 '(diff-hunk-header                    ((t (:background "#242130"))))


 '(font-lock-comment-face ((t (:foreground "#5C6773"  :italic t))))
 '(font-lock-variable-name-face ((t (:foreground "#BFBAB0"  ))))
 '(font-lock-string-face ((t (:foreground "#C2D94C"  ))))
 '(font-lock-builtin-face ((t (:foreground "#F29718"  ))))
 '(font-lock-function-name-face ((t (:foreground "#FFB454"  ))))
 '(js3-function-param-face ((t (:foreground "#F29718"  ))))
 '(js2-function-param ((t (:foreground "#F29718"  ))))
 '(font-lock-warning-face ((t (:foreground "#FFFFFF" :background "#FF7733" ))))
 '(diff-added ((t (:foreground "#C2D94C"  ))))
 '(diff-changed ((t (:foreground "#39BAE6"  ))))
 '(diff-removed ((t (:foreground "#F07178"  ))))
 '(git-gutter:added ((t (:foreground "#C2D94C"  ))))
 '(git-gutter:modified ((t (:foreground "#39BAE6"  ))))
 '(git-gutter:deleted ((t (:foreground "#FF3333"  ))))
 '(git-gutter:untracked ((t (:foreground "#20272C"  ))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#5C6773"  :italic t))))

;; Rainbow delimiters
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#a85054"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#b35e62"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#bb6f73"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#c38083"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#cb9194"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#d3a2a4"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#dbb3b5"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#e3c3c5"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#ebd4d5"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#FF0000"))))
) ;; End face definitions

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'ayu_dark)

;; Local Variables:
;; eval: (when (fboundp 'rainbow-mode) (rainbow-mode +1))
;; End:

;;; ayu_dark-theme.el ends here
