#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3
## Autostart Programs

# Kill already running process
_ps=(waybar mako mpd xfce-polkit)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

# Polkit agent
/usr/lib/xfce-polkit/xfce-polkit &

# Set wallpaper
#swaybg --output '*' --mode fill --image ~/.config/hypr/wallpapers/wallpaper.png &
#swaybg --output '*' --mode fill --image ~/Pictures/cyberpunk_streets_by_seerlight_dbw9m7o-fullview.jpg &
#swaybg --output '*' --mode fill --image ~/Pictures/tunnel_and_a_vending_machine_by_mei_xing_d8uo2by-fullview.jpg &
#swaybg --output '*' --mode fill --image ~/Pictures/crossing_by_the10s_d8yffeb-fullview.jpg &
#swaybg --output '*' --mode fill --image ~/Pictures/archbg.jpg &
swaybg --output '*' --mode fill --image ~/Pictures/zaki-aby-fisheye-hardcoding.jpg &

# Load environment
systemctl --user import-environment

# Apply themes
~/.config/hypr/scripts/gtkthemes &

# Lauch notification daemon (mako)
~/.config/hypr/scripts/notifications &

# Lauch statusbar (waybar)
~/.config/hypr/scripts/statusbar &

# Launch eww
#eww -c $HOME/.config/eww/bar --restart open bar &

# Start mpd
#exec mpd &
